services:
  djangoapp_23103:
    build:
      context: .
    container_name: djangoapp_23103
    command:  sh -c "cd prj && python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./src:/app
    working_dir: /app
    ports:
      - "127.0.0.1:23103:8000"
    depends_on:
      mydb_23103:
        condition: service_healthy

  mydb_23103:
    image: mysql
    container_name: mydb_23103
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: django_db
      MYSQL_USER: django_user
      MYSQL_PASSWORD: django_password
    ports:
      - "127.0.0.1:24103:3306"
    volumes:
      - ./db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
