# Generated by Django 5.1.4 on 2025-01-13 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_module_cm_hours_alter_module_td_hours_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='module',
        ),
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together=None,
        ),
        migrations.DeleteModel(
            name='Module',
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
