# Generated by Django 5.1.5 on 2025-01-25 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_producttype_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointofsale',
            name='type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='nom',
            field=models.CharField(max_length=100),
        ),
    ]
