# Generated by Django 5.1.5 on 2025-01-25 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_pointofsale_type_alter_product_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproduct',
            name='date_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='cartproduct',
            unique_together={('produit', 'panier')},
        ),
    ]
